version: "3.8"

services:
  ffmpeg-api:
    image: ghcr.io/trashcoder/ffmpeg-api:latest
    container_name: ffmpeg-api
    restart: unless-stopped
    ports:
      - "5679:5679"
    volumes:
      - /opt/steam-bot:/data/steam-bot
    networks:
      - n8n_default

networks:
  n8n_default:
    external: true

